<?php /* You should really customize this template … */ ?>
<div id="quafzi_merchantstorepopup" style="display:none">
    <div class="box">
        <div class="content">
            <?php echo $this->__('You requested to switch to our B2B/B2C shop...'); ?>
        </div>
        <div class="buttons">
            <button id="quafzi_merchantstorepopup_cancel"><span><span><?php echo $this->__('Stay in current store'); ?></span></span></button>
            <button id="quafzi_merchantstorepopup_switch"><span><span><?php echo $this->__('Switch store'); ?></span></span></button>
        </div>
    </div>
</div>
